# Generated by Django 4.1.2 on 2022-12-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='image_Rnom',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='image_date',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='image_montant_chiffre',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='image_montant_lettre',
        ),
        migrations.AddField(
            model_name='cheque',
            name='image_DateIss',
            field=models.ImageField(null=True, upload_to='DateIss'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='image_ReceiverName',
            field=models.ImageField(null=True, upload_to='ReceiverName'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='image_amount_digits',
            field=models.ImageField(null=True, upload_to='amount_digits'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='image_amout_letter',
            field=models.ImageField(null=True, upload_to='amout_letter'),
        ),
    ]
